name: $(Build.BuildId)

pool:
  vmImage: 'ubuntu-latest'

trigger:
  branches:
    include:
      - master

resources:
  repositories:
    - repository: templates
      type: git
      name: GHQ_B2B_Delta/golden-CICD-library
      ref: refs/heads/master

variables:
  - group: BEES-GoldenCICD-Microservice-vg
  - group: PricingEngineE2E-GoldenCICD-vg
  - group: BEES-PricingEngine-GoldenCICD-Jdk17-vg


extends:
  template: sre-pipelines/global-pricing-engine/e2e_tests_pipeline.yml@templates ## --> GoldenCICD entrypoint template
  parameters:
    sonarScan: false