sonar.projectKey=java:global-pricing-engine-e2e
sonar.projectName=global-pricing-engine-e2e
sonar.sources=global-pricing-engine-e2e/src/test
sonar.test.inclusions=global-pricing-engine-e2e/src/test/java/*
sonar.sourceEncoding=UTF-8
sonar.language=java
sonar.java.source=17
sonar.java.binaries=global-pricing-engine-e2e/target/test-classes
sonar.java.libraries=global-pricing-engine-e2e/target/*.jar
sonar.junit.reportPaths=global-pricing-engine-e2e/target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=global-pricing-engine-e2e/target/site/jacoco-aggregate-reports/jacoco.xml
sonar.exclusions=
sonar.coverage.exclusions=global-pricing-engine-e2e/src/test/**/*
